name: CI/CD Pipeline Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04  

    steps:
    - name: Cloner le dépôt
      uses: actions/checkout@v3

    - name: Vérifier Docker
      run: docker --version

    - name: Lancer docker-compose
      run: |
        docker-compose -f docker-compose.yml up -d --build
        docker ps

    - name: Nettoyer
      run: docker-compose down
