name: CI/CD Pipeline Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Cloner le dépôt
      uses: actions/checkout@v3

    - name: Configurer Java 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Afficher l'arborescence
      run: ls -R

    - name: Construire le projet Java avec Maven
      run: mvn install -DskipTests -f app_web/pom.xml

    - name: Configurer Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Afficher les versions Docker
      run: |
        docker --version
        docker compose version

    - name: Construire et démarrer les conteneurs
      run: docker compose -f docker-compose.yml up -d --build

    - name: Lister les conteneurs
      run: docker ps

    - name: Arrêter et supprimer les conteneurs
      run: docker compose down

    # Nouvelles étapes ajoutées pour le déploiement sur le serveur
    - name: Sauvegarder les images Docker
      if: github.ref == 'refs/heads/main'  # Exécuté seulement sur push vers main
      run: |
        mkdir -p docker-images
        docker save $(docker compose -f docker-compose.yml config | awk '{if ($1 == "image:") print $2}') -o docker-images/images.tar

    - name: Transférer les fichiers vers le serveur
      uses: appleboy/scp-action@v0.1.7
      if: github.ref == 'refs/heads/main'
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "docker-images/images.tar,docker-compose.yml"
        target: "/home/i.aouinti/app/"
        strip_components: 1

    - name: Déployer sur le serveur distant
      uses: appleboy/ssh-action@v1.0.0
      if: github.ref == 'refs/heads/main'
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/i.aouinti/app
          docker load -i images.tar
          docker compose down || true
          docker compose up -d --build
          rm -f images.tar

    - name: Sauvegarder les images Docker
      run: |
        mkdir -p docker-images
        sudo chmod -R 777 docker-images  # Donne les permissions nécessaires
        docker save $(docker compose -f docker-compose.yml config | awk '{if ($1 == "image:") print $2}') -o docker-images/images.tar
        sudo chmod 644 docker-images/images.tar  # Ajuste les permissions du fichier    

    - name: Transférer les fichiers vers le serveur
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "docker-images/images.tar,docker-compose.yml"
        target: "/home/i.aouinti/app/"
        strip_components: 1
        overwrite: true
        tar_tmp_path: "/tmp"  # Spécifie un répertoire temporaire accessible   
