name: CI/CD Pipeline Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout du code
      uses: actions/checkout@v3

    - name: Mettre à jour apt et installer Docker Compose Plugin
      run: |
        sudo apt-get update -y
        sudo apt-get install -y docker-compose-plugin

    - name: Vérifier Docker et Compose
      run: |
        docker --version
        docker compose version

    - name: Lancer les conteneurs
      run: |
        docker compose -f docker-compose.yml up -d --build
        docker ps

    - name: Nettoyage
      run: docker compose down
