name: CI/CD Pipeline Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Cloner le dépôt
      uses: actions/checkout@v3

    - name: Construire le projet Java avec Maven
      run: mvn clean package -f Projet_docker/app_web/pom.xml

    - name: Configurer Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Afficher les versions Docker
      run: |
        docker --version
        docker compose version

    - name: Construire et démarrer les conteneurs
      run: |
        docker compose -f docker-compose.yml up -d --build

    - name: Lister les conteneurs
      run: docker ps

    - name: Arrêter et supprimer les conteneurs
      run: docker compose down
